Create database LibraryDb
GO

USE "LibraryDb";

Create Table Clients (
Id INT IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(MAX) NOT NULL,
LastName NVARCHAR(MAX),
Phone NVARCHAR(MAX),
Email NVARCHAR(MAX))

CREATE TABLE Books (
Id INT IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(MAX) NOT NULL,
Description NVARCHAR(MAX) NOT NULL)

CREATE TABLE Issuance(
Id INT IDENTITY(1,1) PRIMARY KEY,
ClientId INT REFERENCES Clients(Id) NOT NULL,
BookId INT REFERENCES Books(Id) NOT NULL,
IssuanceDate DATE NOT NULL,
RequiredReturningDate DATE NOT NULL,
ActualReturningDate DATE)